[2024-01-13T11:22:49.650+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T11:22:42.539148+00:00 [queued]>
[2024-01-13T11:22:49.662+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T11:22:42.539148+00:00 [queued]>
[2024-01-13T11:22:49.663+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-13T11:22:49.663+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-13T11:22:49.663+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-13T11:22:49.693+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_infomation_s3> on 2024-01-13 11:22:42.539148+00:00
[2024-01-13T11:22:49.699+0000] {standard_task_runner.py:55} INFO - Started process 4283 to run task
[2024-01-13T11:22:49.701+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'jobinfo_jobplanet', 'create_infomation_s3', 'manual__2024-01-13T11:22:42.539148+00:00', '--job-id', '348', '--raw', '--subdir', 'DAGS_FOLDER/jobinfo_jobplanet.py', '--cfg-path', '/tmp/tmpfdvtt94c']
[2024-01-13T11:22:49.702+0000] {standard_task_runner.py:83} INFO - Job 348: Subtask create_infomation_s3
[2024-01-13T11:22:50.142+0000] {task_command.py:388} INFO - Running <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T11:22:42.539148+00:00 [running]> on host 9d92fdf7265b
[2024-01-13T11:22:50.258+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=jobinfo_jobplanet
AIRFLOW_CTX_TASK_ID=create_infomation_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-01-13T11:22:42.539148+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-13T11:22:42.539148+00:00
[2024-01-13T11:22:50.260+0000] {jobinfo_jobplanet.py:48} INFO - 11111111111111111111111111111111
[2024-01-13T11:22:50.260+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 86, in create_infomation_s3
    driver = jobplanet_login()
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 54, in jobplanet_login
    driver = webdriver.Chrome(executable_path='/usr/src/chrome/chromedriver', options=chrome_options)
TypeError: __init__() got an unexpected keyword argument 'executable_path'
[2024-01-13T11:22:50.273+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=jobinfo_jobplanet, task_id=create_infomation_s3, execution_date=20240113T112242, start_date=20240113T112249, end_date=20240113T112250
[2024-01-13T11:22:50.300+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 348 for task create_infomation_s3 (__init__() got an unexpected keyword argument 'executable_path'; 4283)
[2024-01-13T11:22:50.339+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-13T11:22:50.620+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
