[2024-01-15T11:47:15.555+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jumpit_jobinfo.s3_to_rds scheduled__2024-01-14T11:44:00+00:00 [queued]>
[2024-01-15T11:47:15.564+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jumpit_jobinfo.s3_to_rds scheduled__2024-01-14T11:44:00+00:00 [queued]>
[2024-01-15T11:47:15.565+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-15T11:47:15.565+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-01-15T11:47:15.565+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-15T11:47:15.588+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): s3_to_rds> on 2024-01-14 11:44:00+00:00
[2024-01-15T11:47:15.600+0000] {standard_task_runner.py:55} INFO - Started process 34569 to run task
[2024-01-15T11:47:15.605+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'jumpit_jobinfo', 's3_to_rds', 'scheduled__2024-01-14T11:44:00+00:00', '--job-id', '602', '--raw', '--subdir', 'DAGS_FOLDER/jobinfo_jumpit.py', '--cfg-path', '/tmp/tmpj49wyvaq']
[2024-01-15T11:47:15.606+0000] {standard_task_runner.py:83} INFO - Job 602: Subtask s3_to_rds
[2024-01-15T11:47:15.669+0000] {task_command.py:388} INFO - Running <TaskInstance: jumpit_jobinfo.s3_to_rds scheduled__2024-01-14T11:44:00+00:00 [running]> on host 565f6bcc10b6
[2024-01-15T11:47:15.747+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=jumpit_jobinfo
AIRFLOW_CTX_TASK_ID=s3_to_rds
AIRFLOW_CTX_EXECUTION_DATE=2024-01-14T11:44:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-14T11:44:00+00:00
[2024-01-15T11:47:15.756+0000] {base.py:73} INFO - Using connection ID 's3_conn' for task execution.
[2024-01-15T11:47:15.927+0000] {base.py:73} INFO - Using connection ID 'rds_conn' for task execution.
[2024-01-15T11:47:16.022+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobinfo_jumpit.py", line 134, in s3_to_rds
    cursor.execute(delete_query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1046, 'No database selected')
[2024-01-15T11:47:16.034+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=jumpit_jobinfo, task_id=s3_to_rds, execution_date=20240114T114400, start_date=20240115T114715, end_date=20240115T114716
[2024-01-15T11:47:16.068+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 602 for task s3_to_rds ((1046, 'No database selected'); 34569)
[2024-01-15T11:47:16.103+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-15T11:47:16.122+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
