[2024-01-15T11:56:14.792+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jumpit_jobinfo.s3_to_rds scheduled__2024-01-14T11:56:00+00:00 [queued]>
[2024-01-15T11:56:14.801+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jumpit_jobinfo.s3_to_rds scheduled__2024-01-14T11:56:00+00:00 [queued]>
[2024-01-15T11:56:14.802+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-15T11:56:14.802+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-01-15T11:56:14.802+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-15T11:56:14.819+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): s3_to_rds> on 2024-01-14 11:56:00+00:00
[2024-01-15T11:56:14.826+0000] {standard_task_runner.py:55} INFO - Started process 35041 to run task
[2024-01-15T11:56:14.830+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'jumpit_jobinfo', 's3_to_rds', 'scheduled__2024-01-14T11:56:00+00:00', '--job-id', '616', '--raw', '--subdir', 'DAGS_FOLDER/jobinfo_jumpit.py', '--cfg-path', '/tmp/tmpv6pinula']
[2024-01-15T11:56:14.830+0000] {standard_task_runner.py:83} INFO - Job 616: Subtask s3_to_rds
[2024-01-15T11:56:14.891+0000] {task_command.py:388} INFO - Running <TaskInstance: jumpit_jobinfo.s3_to_rds scheduled__2024-01-14T11:56:00+00:00 [running]> on host 565f6bcc10b6
[2024-01-15T11:56:14.980+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=jumpit_jobinfo
AIRFLOW_CTX_TASK_ID=s3_to_rds
AIRFLOW_CTX_EXECUTION_DATE=2024-01-14T11:56:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-14T11:56:00+00:00
[2024-01-15T11:56:14.992+0000] {base.py:73} INFO - Using connection ID 's3_conn' for task execution.
[2024-01-15T11:56:15.162+0000] {base.py:73} INFO - Using connection ID 'rds_conn' for task execution.
[2024-01-15T11:56:15.274+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobinfo_jumpit.py", line 134, in s3_to_rds
    cursor.execute(delete_query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1046, 'No database selected')
[2024-01-15T11:56:15.281+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=jumpit_jobinfo, task_id=s3_to_rds, execution_date=20240114T115600, start_date=20240115T115614, end_date=20240115T115615
[2024-01-15T11:56:15.299+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 616 for task s3_to_rds ((1046, 'No database selected'); 35041)
[2024-01-15T11:56:15.323+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-15T11:56:15.339+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
